### ISSUE TITLE
As_of and batches don't work together

### ISSUE THREAD

**Issue by gregmojonnier** [RailsEventStore/rails_event_store#1037]
In my rails app using RailsEventStore version `2.1.0`, I noticed when running `Rails.configuration.event_store.read.stream('a_stream_name').as_of`, the as_of specifier was resulting in duplicate events getting returned. I didn't see the issue without the `as_of` specifier or when using `as_at`. I think I pinpointed the problem area of rails_event_store, from what I can tell as_of and batches don't work together. 

Here is a minimal patch file modifying `event_repository_spec.rb` and `event_repository_lint.rb` to demonstrate what I believe to be a bug:
```
diff --git a/rails_event_store_active_record/spec/event_repository_spec.rb b/rails_event_store_active_record/spec/event_repository_spec.rb
index 2791154d..445bbc4b 100644
--- a/rails_event_store_active_record/spec/event_repository_spec.rb
+++ b/rails_event_store_active_record/spec/event_repository_spec.rb
@@ -53,6 +53,26 @@ module RailsEventStoreActiveRecord
       )
     end
 
+    let(:stream_name) { 'abc' }
+    specify "as_of and batches don't work together" do
+      # append 2 events to stream out of order(by valid_at)
+      repository.append_to_stream(
+        [RubyEventStore::SRecord.new(valid_at: Time.new(2023, 3, 3))],
+        RubyEventStore::Stream.new(stream_name),
+        RubyEventStore::ExpectedVersion.none
+      )
+      repository.append_to_stream(
+        [RubyEventStore::SRecord.new(valid_at: Time.new(2021, 1, 1))],
+        RubyEventStore::Stream.new(stream_name),
+        RubyEventStore::ExpectedVersion.any
+      )
+
+      expect(specification.to_a.size)                .to eq(2) # correct
+      expect(specification.as_at.to_a.size)          .to eq(2) # correct
+      expect(specification.as_of.to_a.size)          .to eq(3) # incorrect? Batches and as_of/valid_at ordering seem to not play nice.
+      expect(specification.as_of.limit(10).to_a.size).to eq(2) # correct. Adding a limit seems to bypass the issue.
+    end
+
     specify "does not confuse all with GLOBAL_STREAM" do
       repository.append_to_stream(
         [RubyEventStore::SRecord.new(event_id: "fbce0b3d-40e3-4d1d-90a1-901f1ded5a4a")],
diff --git a/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb b/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
index bb028de0..51254f3a 100644
--- a/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
+++ b/ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
@@ -1,11 +1,13 @@
 module RubyEventStore
+  class SRecordTestEvent < RubyEventStore::Event
+  end
   # @private
   class SRecord
     def self.new(
       event_id:   SecureRandom.uuid,
       data:       {},
       metadata:   {},
-      event_type: 'SRecordTestEvent',
+      event_type: 'RubyEventStore::SRecordTestEvent',
       timestamp:  Time.new.utc,
       valid_at:   nil
     )
```

I'm pretty sure the issue comes from this area of the code, but am not totally sure on the best fix given my inexperience with the RailsEventStore codebase:
https://github.com/RailsEventStore/rails_event_store/blob/f90087b9dddfe958305e22941a0c1b301309925f/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb#L25-L29

Does this look like a bug? If so, would you be able to estimate when a fix for as_of might be released? Thank you!

**Comment by pawelpacana** [comment]
Thanks for the report, I'll have a look on it later today

**Comment by pawelpacana** [comment]
First of all thank you for the effort of reproducing the issue and providing a test case — that helped. I've made it a bit more specific to EventRepository: https://github.com/RailsEventStore/rails_event_store/commit/72157c17bc4a3cd86cf2f443d248f59c738b6fd5

`EventRepository#read` expects `SpecificationResult` to perform a read and is expected to return `RubyEventStore::Record` (sort of, it could an Enumerator returning those). 

This ensures we'll get batched reads: `repository.read(specification.in_batches.result).to_a`

You've achieved the same calling `specification.to_a`, which [implies](https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store/lib/ruby_event_store/specification.rb#L171-L191) batching. The drawback is that it involves few more collaborators (i.e. mappers) and returns `RubyEventStore::Event` objects.

> Does this look like a bug?

Definitely a bug. It boils down to this:
- there are two batch reader implementations, one that relies on OFFSET + LIMIT for querying and one based on monotonic integer ids (quite like `ActiveRecord::Batches` works: https://api.rubyonrails.org/v6.1.3.1/classes/ActiveRecord/Batches.html#method-i-find_each)
- one batch reader has significantly better performance over large sets of events due to the way how relational databases work (https://developer.wordpress.com/2014/02/14/an-efficient-alternative-to-paging-with-sql-offsets/), but it also requires the monotonicity over `id` column to be maintained
- with `as_at` and `as_of` reads are reordered and that monotonicity of `id` column in result set is broken, affecting BatchEnumerator

I've decided to fallback to OFFSET + LIMIT based batching in case of bi-temporal queries (that is using `as_at` and `as_of`). 

I believe there's a way to make `RailsEventStoreActiveRecord::BatchEnumerator` work with bi-temporal queries in the future.

**Comment by pawelpacana** [comment]
> would you be able to estimate when a fix for as_of might be released?

The 2.2.0 release is scheduled for tomorrow

**Comment by pawelpacana** [comment]
Released: https://github.com/RailsEventStore/rails_event_store/releases/tag/v2.2.0

**Comment by gregmojonnier** [comment]
Thank you so much for the explanation and quick turnaround, really appreciate it! I'll start using v2.2.0 and report back if I encounter any issues with it.
