### ISSUE TITLE
Unsupported adapter when running migration (2.11.1)

### ISSUE THREAD

**Issue by philipguedes** [RailsEventStore/rails_event_store#1650]
Hi! 

I'm trying to configure **rails_event_store** `2.11.1` in an existing rails project using the [Advanced setup](https://railseventstore.org/docs/v2/install/#advanced-setup).

When I try to setup the data model using

```sh
bin/rails generate rails_event_store_active_record:migration
```

I'm getting the one-liner error

```sh
Unsupported adapter
```

I downgraded to `2.9.1`, used the same command and it worked like a charm.

**Comment by lukaszreszke** [comment]
Hi @philipguedes,

What database are you using?

**Comment by philipguedes** [comment]
Hey @lukaszreszke thanks for replying.

> Hi @philipguedes,
>
> What database are you using?

I'm using postgres 15+

If it comes in handy, I [created a repo](https://github.com/philipguedes/rails-event-store_dummy) to reproduce this problem

**Comment by lukaszreszke** [comment]
Thanks for the repo with repro reproduction @philipguedes. Indeed it helped a lot. 

I found the root cause of the issue. 

In `RubyEventStore::ActiveRecord` we define supported adapters:
https://github.com/RailsEventStore/rails_event_store/blob/master/ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/verify_adapter.rb#L8

Supported adapters are generally:
`SUPPORTED_ADAPTERS = %w[mysql2 postgresql sqlite].freeze`

Both for RES 2.9.1 and RES 2.11.1 the adapter introduces itself as postgis: 
```
irb(main):001:0>         ::ActiveRecord::Base.connection.adapter_name.downcase
=> "postgis"
```

In 2.10 the code with the `VerifyDataType` was released, so now it blocks the migration as `postgis` is not supported.

I'll notify you when the fix is rolled out. Thanks for reporting this issue.

**Comment by pawelpacana** [comment]
So it's an additional gem that provides postgresql-like adapter, that introduces itself as `postgis`:
https://github.com/rgeo/activerecord-postgis-adapter/blob/master/lib/active_record/connection_adapters/postgis_adapter.rb#L26-L29

**Comment by fidel** [comment]
Hey @philipguedes!

The issue you've experienced is resolved on master with commit: https://github.com/RailsEventStore/rails_event_store/commit/b2d7396fdf42f22aa11832e232dacffbfa266b7c

We should release it officially soon, but you can start using it right away with this entry in your `Gemfile`:

```
gem "rails_event_store", github: "RailsEventStore/rails_event_store", ref: "b2d7396"
```

Thanks for the detailed report and happy coding!

**Comment by pjurewicz** [comment]
Hey @philipguedes,
this issue is fixed in rails_event_store v. 2.12.0.
thank you for your engagement.
