### ISSUE TITLE
Defining the schema of an event

### ISSUE THREAD

**Issue by paneq** [RailsEventStore/rails_event_store#27]
Maybe `dry-validation` could be a good candidate for defining events schema?
- http://dry-rb.org/news/2016/03/16/announcing-dry-rb/

**Comment by mlomnicki** [comment]
I think that RES shouldn't be opinionated about your events. Instead, it should require an event to implement a certain interface. Currently, an event should provide 2 methods
* event_id
* to_h

For example, this is how you can utilize dry-types.

```ruby
class Event < Dry::Types::Value
  def self.inherited(klass)
     super
     klass.attribute :event_id,  Types::String.default { SecureRandom.uuid }
     klass.attribute :timestamp, Types::DateTime.default { Time.now }
  end

  def to_h
    {
      event_id: event_id,
      data: super.except(:event_id, :timestamp),
      metadata: { timestamp: timestamp }
    }
  end
end

class OrderPlaced < Event
  attribute :order_id, Types::Int
  attribute :ship_at,   Types::DateTime
end

class ProductPriceChanged < Event
  attribute :product_id, Types::UUID
  attribute :new_price, Types::Money
end
```

In the same way, you could utilize dry-validation or anything else. The point is, RES doesn't have 
to know about your choices, nor support them.
In my opinion, it would be enough to prepare some docs and show how to use RES with dry-types/dry-validation/etc.

**Comment by gottfrois** [comment]
+1 about RES defining a contract for the event implementation instead of a schema

**Comment by paneq** [comment]
+1

I think we need

* `event_id`
* `event_type`
* `to_h`

I am not sure about metadata and stream.

**Comment by mpraglowski** [comment]
`stream` is not the attribute of an event - it is logical concept for grouping events. 
I think an event could be "stored" in more than 1 stream - projections.

`metadata` is like a http headers for a request, not the data itself but still part of the request. `metadata` could be very important (i.e. when you build an audit log based on stream of events) - we should keep that in event's contract.

**Comment by gottfrois** [comment]
> metadata could be very important 

+1 I use this field to store routing information about the event

**Comment by gottfrois** [comment]
Wanted to give a shot do dry-types in order to define a schema for my events but here are the issues I encountered during the process:

- ruby_event_store injects a `timestamp` into the `metadata` hash https://github.com/arkency/ruby_event_store/blob/master/lib/ruby_event_store/client.rb#L81

I tend to think we should let the client decide how to build his events, it would be simple enough to add that timestamp on the application side by defining some `Events::Base` class or something. Instead of magically injecting something in his behalf. In my case for example, the `metadata` hash was frozen from the start so it failed when reaching that point.

2. events are built by passing the following signature to the `initialize` method: `(event_id:, data:, metadata:)`

Having relevant event data nested in `data` makes schema definition harder. I would prefer if we simply pass attributes to the initialize method like a regular object:

```
event = Event.new(foo: 'foo', bar: 'bar', metadata: { ... })
```

with reserved word for `event_id` probably and with default uuid like today.

Like @mlomnicki said, we should probably just ask for an interface rather than magically injecting data and enforce a data schema.

What do you guys think?

**Comment by paneq** [comment]
@gottfrois interesting points.

We don't want reserved keys. `event_id` is something we use regularly in our projects which are about Events (as in concerts, workshops) etc and use it probably in 80% of our domain events :)

**Comment by gottfrois** [comment]
@paneq interesting, did not think about that as well.

I don't think we should store events differently, `data` nesting is good here. I'm thinking more about how the event instance is build but can't find a good solution to propose right now :-/

**Comment by mpraglowski** [comment]
> ruby_event_store injects a timestamp into the metadata hash...

This is a timestamp of event publication. It is similar to you go to post some message at the post office, you handle your message (letter in envelope) that is "frozen" - but the post office clerk will hit the envelope with stamp adding a time when it has been handled. This is exactly what is RubyES doing.

And it could not be set earlier because the moment of event creation is not the same as the moment of publication.

**Comment by gottfrois** [comment]
@mpraglowski makes sense, thanks for the clarification of the usecase here.

**Comment by pawelpacana** [comment]
A working example of `dry-types` event schema is present in https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/f9637b37ed69f586e73733d0465f287348d22815/lib/event.rb.

An alternative way to describe schema with `ClassyHash` has been described in [Domain-Driven Rails](https://blog.arkency.com/domain-driven-rails/) book.
