### ISSUE TITLE
Auto expected version fails if you has old events with position null for the same stream name

### ISSUE THREAD

**Issue by kln** [RailsEventStore/rails_event_store#425]
Hi there!

I've first implemented `event store` without defining an `expected_version`. Now that I implemented it with `:auto`, when the first event is published, the `EventInStream` query order by `position DESC`, it returns a stream with same `stream_name` and position `null`, so position receives `-1` (POSITION_DEFAULT) and saves the new stream with position `0`. 

https://github.com/RailsEventStore/rails_event_store/blob/master/rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb#L52

https://github.com/RailsEventStore/rails_event_store/blob/3d16508da26376e2fd7c6d7c6043872b62a1e660/ruby_event_store/lib/ruby_event_store/expected_version.rb

When the second event runs the query, it returns the stream with the same `stream_name` and position `null` again (because in that order null value cames first than integers), so it tries to save it with position `0` and raises `RubyEventStore::WrongExpectedEventVersion`.

I solved it updating the event streams on database setting the position according to created_at, but what I think the EventInStream query could do is search for events where the position is not null.

Example:
```
STREAM_NAME   POSITION  
Order-1       null (old event)
Order-1       0 (first event with expected_version: :auto)
```

If I try to publish another event as below:
`rails_event_store_client.publish(event, stream_name: 'Order-1', expected_version: :auto)` => raises RubyEventStore::WrongExpectedEventVersion

Sugestion:
`last_stream_version = ->(stream_) { EventInStream.where.not(position: nil).where(stream: stream_.name).order("position DESC").first.try(:position) }`

What do you think about?

**Comment by paneq** [comment]
It's a known limitation. The documentation says:

> You should never mix expected_version: :any with :auto or explicit number (Integer) for the same stream name.

in http://railseventstore.org/docs/expected_version/

As you said:

> I solved it by updating the event streams on database setting the position according to created_at,

That's a proper fix. If you mix `:auto` and `:any` (which gives `NULL`) then we really don't have a fast way to know the real order. You know that you first had `NULL`s and then you stopped doing it. But the library can't be sure you are not still mixing them using `auto`, `any`, `auto`, `any` alternately.

> last_stream_version = ->(stream_) { EventInStream.where.not(position: nil).where(stream: stream_.name).order("position DESC").first.try(:position) }

Technically we could go with this suggestion but I don't see what it improves. It does not make the stream reliably ordered and it does not fix the fact that same stream was used with different semantics. It fixes an indicator of a bigger problem instead of that bigger problem itself, I believe.

Related: #420

**Comment by kln** [comment]
> It fixes an indicator of a bigger problem instead of that bigger problem itself, I believe.

Makes sense

**Comment by paneq** [comment]
Thanks for the question @kln . Can you tell us more about what version of RES are you using and since when :) Have a nice weekend.
