### ISSUE TITLE
Integration with ActiveAdmin

### ISSUE THREAD

**Issue by jeantristan** [RailsEventStore/rails_event_store#438]
Hello,
Is there an easy way to read a stream and integrate it in ActiveAdmin ?
Thanks

**Comment by paneq** [comment]
@jeantristan 

I have no idea as I've never used ActiveAdmin.

This might be helpful:

* https://activeadmin.info/2-resource-customization.html#customizing-resource-retrieval
* http://railseventstore.org/docs/read/

My guess is that since AA is very ActiveRecord oriented it might be much easier/faster to write custom controller to achieve whatever you need rather than to try to integrate with AA functionalities but that's just a guess from me. Maybe it really is that flexible but hard to say as you haven't stated very clearly what you would like to achieve. Browsing events functionality? You might give RES Browser a try http://railseventstore.org/docs/browser/

**Comment by jeantristan** [comment]
Thanks for your quick response and for pointing me the browser. You're right the purpose is to browse events. So I guess is better to have a custom controller cause AA is really ActiveRecord oriented.

Thanks you very much!
