### ISSUE TITLE
API for changing events

### ISSUE THREAD

**Issue by swistak35** [RailsEventStore/rails_event_store#443]
From time to time, developers may decide that they want to modify the events, i. e. enrich them. Obviously we can agree that there's always other solution (like enrichment in application code, for example). However, considering the fact that we usually use SQL database underneath, there's probably no technical reason why wouldn't we provide at least some basic API to change the events. Now, changing events require using internal details of repository, pushing serialized record through mappers (in two directions) and finally also calling some raw persistence calls (like `save!` in case of Active Record).

**Comment by joelvh** [comment]
@swistak35 I was thinking about this exact thing today as well, as we have a desire to rewrite event data rather than handle in code early in a project when some naming has changed. I'm curious how you are thinking of adding this capability. I see it as something similar to the projection functionality, but also would want to implement this in a way that doesn't encourage abuse or using it inefficiently.

**Comment by paneq** [comment]
```
require 'ruby_event_store/danger_zone'

# events: contains events with same ID as existing ones but updated data or metadata
client.overwrite(events)
```

I believe that would be sufficient top-level API.

This API would be useful for remapping with different mapper. You instantiate events with one Client instance using old mapper, change them (or not) and pass to another client (with new mapper configured) to `overwrite` and it updates their serialized value in DB.

It would probably be implemented similar to:

```ruby
    def overwrite(events)
      serialized_events = serialize_events(events) # no enrichment !!!
      repository.overwrite(serialized_events)
      self
    end
```

**Comment by paneq** [comment]
Whole operation of overwriting N events should be atomic imho. It should not affect streams the event is in.

I can confirm it would be useful in other projects as well!

**Comment by joelvh** [comment]
I assume there would still be a need for mapping events to handle old and new format, and then the old format of the event can be removed from the code in a subsequent deployment — is that how you think of it? If the event name stays the same, the event class needs to somehow tell if it’s old or new data format until the “migration” of the event data is complete.

I haven’t messed with this yet, but imagine that’s the approach.

**Comment by swistak35** [comment]
In our case it was like this:
1) handle both old and new version in application code (by enrichment, for example)
2) overwrite events' data
3) remove application code handling old version

So we didn't need from event store anything more than the API to overwrite. I imagine there could be some API supporting enrichmnet of events in application code, but I would say that could be separate issue :) If there would be an API for such enrichment, maybe we could event have some automated script to overwrite all events using enriched attributes...

**Comment by paneq** [comment]
> You instantiate events with one Client instance using old mapper, change them (or not) and pass to another client (with new mapper configured) to overwrite and it updates their serialized value in DB.

I realized this can be done with:

```ruby
    def overwrite(events, mapper: self.mapper)
      serialized_events = serialize_events(events, mapper) # no enrichment !!!
      repository.overwrite(serialized_events)
      self
    end
```

so you can serialize to a new mapper even if you are not using it. But this might not be needed having @joelvh questions in mind:

> I assume there would still be a need for mapping events to handle old and new format, and then the old format of the event can be removed from the code in a subsequent deployment — is that how you think of it?

That's necessary if you need a rolling-deploy.  Otherwise, not.

> 1. handle both old and new version in application code (by enrichment, for example)

Or by using a mapper which can recognize events based on something and delegate between 2 code versions.

```ruby
class NewMapper
  def initialize(old_mapper: RubyEventStore::Mappers::Default.new)
    @old_mapper = old_mapper
  end

  def event_to_serialized_record(message)
    return old_mapper.event_to_serialized_record(message) unless new_format_of_message?(message)
    new_mapping_logic_here
  end

  def serialized_record_to_event(record)
    klass = Object.const_get(record.event_type)
    return old_mapper.serialized_record_to_event(record) unless new_format_of_serialized_message?(message)
    new_mapping_logic_here
  end
```

> 2. overwrite events' data

Current code writing new events in new version. Live migration rewriting old event's serialization.

> 3. remove application code handling old version

Your new mapper no longer delegates to old one when all messages are rewritten.

> If the event name stays the same, the event class needs to somehow tell if it’s old or new data format until the “migration” of the event data is complete.

Unfortunately that's correct. Unless you can inspect the data to detect how it was serialized. You don't need to recognize from all possible version. Just between the new and old one you have in code.

Also, if the `change` API returns an event with a different "type" then it is going to overwrite event's name. I hope the test cases are going to guide us.

**Comment by paneq** [comment]
PR: #444

**Comment by joelvh** [comment]
Should this be closed?

**Comment by joelvh** [comment]
I would think that the "pipeline" way  of combining mappers and remapping is where this topic is shifting

**Comment by pawelpacana** [comment]
I have some doubts regarding the naming but otherwise this is done. Any discussion on improvements will be a new issue.
