### ISSUE TITLE
Browser UX

### ISSUE THREAD

**Issue by gabrielrotbart** [RailsEventStore/rails_event_store#568]
- In the browser documentation https://railseventstore.org/docs/browser/ the screenshot shows a handy search field. But I can't see that it was implemented. Am I missing something?

- The `Stream Browser` link points to root. I can't see how to browse stream. I found the `/streams/:id` route in the code and am using it. Can we have a way to search by stream?

- Finally, as per #549. It would be good to have a filter for events by type.

Thanks for all the amazing work so far. Using RES is having a really positive effect simplifying our architecture

**Comment by pawelpacana** [comment]
Thank you for your kind words, it made my day!

Browser documentation features a screenshot from an older version of the browser that was distributed with RES v0.22. Functionality present at that time has been captured on a GIF: https://giphy.com/gifs/rails-event-store-3o6fJacEiYvOPRK8CI/fullscreen.

Search functionality has been then removed in v0.25 via this commit: https://github.com/RailsEventStore/rails_event_store/commit/be75235cca46a649949c125b3e313f06826eb59a. In short it was a client-side filtering of a loaded set of events. With the introduction of paging on server side, it made little sense to keep it just for filtering of events on a current page.

For a reasonable search functionality we'd likely have to introduce an API to Client in order to retrieve matching events in a given stream. For large streams like the global one it could mean that we have to use some form of full-text search index. So far we still support MySQL, PostgreSQL and Sqlite which makes the general solution tricky. And there could non-relational-database adapters to complicate this even more (and a primary reason why this has to be a Client API). But I might be wrong here and I'm open for ideas.

I know a team that implemented their browser / audit log with a help of Elasticsearch cluster. Each published event is added to the index via the event handler. Then the UI part interacts with search index. Once event ids of searched events are known, RES retrieves [them](https://railseventstore.org/docs/read/#reading-specified-events).  This is what I'd generally advise for a production use case. 

I can't imagine RES itself depending on Elasticsearch just for the browser part. That however makes room for a great extension in a separate gem or a browser alternative for those keen on introducing another moving part in the infrastucture. I could even imagine a browser as a hosted 3rd party service, if that makes sense given legal side of processing someone's data. 

Apart from browsing events in a given stream, we used to have browsing of stream names. The route you found is a remaining part of it, that allowed jumping into chosen stream. Btw. it is used in https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/app/helpers/application_helper.rb for for the same purpose.

There were [reasons](https://github.com/RailsEventStore/rails_event_store/issues/212) why stream browser had to [go](https://github.com/RailsEventStore/rails_event_store/pull/298) in v0.28. It has its place with suitable implementation. At that time it was more of a hack that did not survive.

Filtering by event type in browser is lucky to already have corresponding API part in Client but no one approached it yet, even on a wireframe. Feel free to explore this idea as well.

**Comment by swistak35** [comment]
@gabrielrotbart We've just released version 0.40 which includes new improvements in RES Browser :)

Check the changelog: https://github.com/RailsEventStore/rails_event_store/releases/tag/v0.40.0
