### ISSUE TITLE
Allow to add custom "related streams" of a stream in browser

### ISSUE THREAD

**Issue by swistak35** [RailsEventStore/rails_event_store#666]
Very often, for some stream, especially aggregates, there are other streams which are "related".

For example, we may have `Ordering::Order` and `Shipping::Order` stream, and these are likely to be bound by 1-1 relation or similar. It would be nice to have a link (by link, I mean HTML link, not event store link :) ), from one stream to another, when viewing them in browser. That would ease the debugging and make it faster to move between data.

The idea is that this would be completely up to developers to provide the `RelatedDomainStreamsQuery` class, which would for example respond to method `call(stream_name)`. When viewing stream `Ordering::Order`, the browser would call `related_domain_streams_query.call(currently_viewed_stream)`, which would respond with list of associated streams (strings). The developer could of course use any code he wants, in especially probably use some already defined read models in the application or RDBMS resources.

What do you think?

**Comment by swistak35** [comment]
We could also extend that idea naturally to display "domain related streams" / events when viewing particular domain event.

**Comment by mpraglowski** [comment]
Maybe instead of implementing `RelatedDomainStreamsQuery ` query we could implement more generic stream metadata mechanism. Something similar to https://eventstore.org/docs/server/metadata-and-reserved-names/index.html & https://eventstore.org/docs/dotnet-api/stream-metadata/index.html

That would allow us to push related streams and maybe other data i.e. when stream is created, some age control (MaxAge in GES, not implemented yet on RES), stream ACLs, stream state (if we ever implement soft & hard delete of streams).

**Comment by pawelpacana** [comment]
> browser would call related_domain_streams_query.call(currently_viewed_stream), which would respond with list of associated streams (strings)

I like that. We can start with `->(stream_name) { [] }`. 

It also leaves door open for ideas like "generic stream metadata mechanism" without actually changing API.
