### ISSUE TITLE
Store event in database

### ISSUE THREAD

**Issue by tranhoangvuit** [RailsEventStore/rails_event_store#730]
We're very like this gem, it's very useful and easy to use. But when we implement it and we got issue with storage. Right now we store it with our current database(Postgres) and our database grow so fast (events is 40-60% storage). To be clear on flow and separate with main database, do we have anyway to store it separately with main database? like we have 1 database to store rails event store and one database to store main database. When we have any issue we can recovery from event store as well. Thank you so much.

**Comment by leandronsp** [comment]
We are facing the same issue at this time. Main database is growing faster. 

At first glance, our approach would be writing a new Repository that inherits from `RailsEventStoreActiveRecord::EventRepository` and overrides the needed parts using different AR models.

However such a code it's very likely to get outdated as explained [here](https://railseventstore.org/docs/repository/#community-event-repositories). I'd suggest that's better to enhance this very gem `rails_event_store` in order to have a new type of repository, like `RailsEventStoreActiveRecord::WhateverDatabase::EventRepository`. (I'm not keen of this "custom repository as a gem" thing because it gets outdated fast and makes harder future upgrades)

What are your thoughts @pawelpacana? If you guys agree I could try to start something on that matter and submit a Pull Request when possible.

**Comment by mpraglowski** [comment]
@tranhoangvuit @leandronsp I'm experimenting with multiple databases support based on Active Record 6 new features - maybe you could find this interesting 
https://github.com/RailsEventStore/rails_event_store/compare/multiple-databases-repository

**Comment by leandronsp** [comment]
Thanks for sharing it @mpraglowski! I'll definitely check this out and start some experimentation.
