### ISSUE TITLE
after upgrade from 1.1.0 to 1.1.1 events are reported twice in tests

### ISSUE THREAD

**Issue by tomasc** [RailsEventStore/rails_event_store#756]
The following test fails on 1.1.1:

```ruby
class DoRestoreBaseTest < RailsEventStore::TestCase
      let(:base) { create :page_base }
      let(:base_id) { base.id }

      let(:stream_name) { BaseAggregate.stream_name(base_id) }

      before do
        arrange(stream_name, [
          BaseDiscarded.new(data: { base_id: base_id, discarded_at: Time.current })
        ])
      end

      it "BaseRestored event is published" do
        published = act(stream_name, DoRestoreBase.new(base_id: base_id))
        assert_changes(published, [BaseRestored.new(data: { base_id: base_id })])
      end
    end
```

The published queue contains 2 of the same events. Happens only on 3 tests in my suite.
I tried to comment out all other bus registrations and store subscriptions, but with same result.

I use the standard helpers:

```ruby
    def arrange(stream_name, events)
      events.each { |e| event_store.publish(e, stream_name: stream_name) }
    end

    def act(stream_name, command)
      before = event_store.read.stream(stream_name).each.to_a
      command_bus.(command)
      after = event_store.read.stream(stream_name).each.to_a
      after.reject { |a| before.any? { |b| a.event_id == b.event_id } }
    end

    def assert_changes(actuals, expected)
      expects = expected.map(&:data)
      assert_equal(expects, actuals.map(&:data))
    end

    def assert_no_changes(actuals)
      assert_empty(actuals)
    end
```

Perhaps it has something to do with reading from the event_store? (I use fresh `RailsEventStore::Client.new` for each test):

```ruby
  before do
      @original_event_store = AggregateRoot.configuration.default_event_store
      AggregateRoot.configuration.default_event_store = RailsEventStore::Client.new
    end

    after do
      AggregateRoot.configuration.default_event_store = @original_event_store
    end
```

**Comment by mpraglowski** [comment]
Hi @tomasc 
Could you provide a failing test case (PR here)? I could not reproduce this issue - maybe I'm missing something.
Have you checked the repository before the test run ? `RailsEventStore::Client.new` will use new `RailsEventStoreActiveRecord::EventRepository`, but the database records could be still present after some previous tests.

Maybe you could try to run this test with:
`RailsEventStore::Client.new(repository: RubyEventStore::InMemoryRepository.new)`

**Comment by tomasc** [comment]
Thanks @mpraglowski – turns out the issue was in my configuration. I have been replacing the `AggregateRoot` event store, but not the main one in Rails config. Adjusting that (and using the `InMemoryRepository.new` per your suggestion) did the trick.

**Comment by pawelpacana** [comment]
I believe I'm experiencing this as well on `RailsEventStoreActiveRecord::EventRepository` repository with PostgreSQL. Same repository on sqlite did not exhibit such problem.

> Maybe you could try to run this test with:
RailsEventStore::Client.new(repository: RubyEventStore::InMemoryRepository.new)

Btw. changing repositories does not help to pinpoint issues present within one particular repository.

**Comment by pawelpacana** [comment]
Well that one was nasty to figure out 😔

The culprit is the test setup, specifically how `arrange` works:

```ruby
def arrange(stream_name, events)
  events.each { |e| event_store.publish(e, stream_name: stream_name) }
end
```

Notice how `publish` does not use `expected_version`. On the other hand there was an aggregate with `AggregateRoot` (at least in my case and cqrs-es-sample-with-res application). 
Aggregate repository strores events with explicit `expected_version`. It does so to enable optimistic concurrency control. 

Mixing expected version numbers is painful and not going to work, because one cannot sort reliably by `position` in stream when some positions are `nil`:
https://railseventstore.org/docs/v1/expected_version/#beware. 
Unfortunately there is no mechanism to detect such violation in test/development.

After all I'm happy this is test-setup-only issue and not a deeper problem in RES.

Post scriptum: This issue can be masked under sqlite becasue of different order when sorting column by values of NULL, Integer than postgres.

**Comment by pawelpacana** [comment]
Aside: we're arranging test setup with commands in https://github.com/arkency/aggregates/blob/66e56d6683eb0f39b669c7bb280a9efdac793386/test/test_helper.rb
